### ISSUE TITLE
Proposal: Include Drivers In This Repository

### ISSUE THREAD

**Issue by EmperorArthur** [pysigrok/pysigrok#1]
While the plugin system is extremely useful, the recommended approach of creating a new module for every single device reduces accessibility. Especially when a single driver covers multiple devices, with little or not per device configuration.  Eg, Sigrok's [serial-dmm](http://sigrok.org/gitweb/?p=libsigrok.git;a=blob;f=src/hardware/serial-dmm/api.c;h=9af2bd5bc56e8b79a035fa78a24d613f8c6aa036;hb=HEAD) driver.

Providing drivers bundled with the core also prevents communication.  The more repos there are the more likely something will be missed, and the more fragmented the community becomes.  A few is fine, but the NPM "left-pad" issue shows what happens when minimalism goes too far.

**Comment by tannewt** [comment]
I’d rather not have drivers here because then I’d have to maintain them. My goal is to avoid that. (That centralized model is currently failing with sigrok.)

I’m ok if another repo supports multiple devices though. The libsigrokdecode repo is an example that has many individual plugins in one repo.

We could also have a list here that links to other known repos.
